name: "Slack Notifier CLI"
description: "Create a change log based of git commit history"
inputs:
  job-type:
    description: ""
    required: true
  job-status:
    description: ""
    required: true
  service-name:
    description: "The name of your service (if you don't like the default)"
    required: false
  service-emoji:
    description: "The emoji you want to use for your service!"
    required: false
  slack-app-token:
    description: ""
    required: true
  slack-channel-id:
    description: ""
    required: true
  slack-message-id:
    description: ""
    required: false
secrets:
  GHL_USERNAME:
    required: true
    description: 'Github Username'
  GHL_PASSWORD:
    required: true
    description: 'Github Password'
  GH_TOKEN:
    required: true
    description: 'Github Token'
outputs:
  slack-message-id:
    description: "Slack message id that was published"
    value: ${{ steps.slack-notifier.outputs.SLACK_MESSAGE_ID }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Test Github CLI download slack notifier cli
      env:
        GHL_USERNAME: ${{ secrets.GHL_USERNAME }}
        GHL_PASSWORD: ${{ secrets.GHL_PASSWORD }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh release download v1.2.7 --repo monta-app/slack-notifier-cli
        chmod +x ./slack-notifier-cli
      shell: bash
    - name: Run slack notifier cli
      id: slack-notifier
      env:
        PUBLISH_SLACK_JOB_TYPE: ${{ inputs.job-type }}
        PUBLISH_SLACK_JOB_STATUS: ${{ inputs.job-status }}
        PUBLISH_SLACK_SERVICE_NAME: ${{ inputs.service-name }}
        PUBLISH_SLACK_SERVICE_EMOJI: ${{ inputs.service-emoji }}
        SLACK_APP_TOKEN: ${{ inputs.slack-app-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        SLACK_MESSAGE_ID: ${{ inputs.slack-message-id }}
      run: ./slack-notifier-cli
      shell: bash
