name: "Slack Notifier CLI"
description: "Create a change log based of git commit history"
inputs:
  status:
    description: "Github Action Status"
    required: true
  title:
    description: "Title of the status update"
    required: true
  slack-token:
    description: "Slack App API Token used for publishing changelog"
    required: true
  slack-channel-id:
    description: "Which slack channel should this be published to"
    required: true
  slack-message-id:
    description: "Which message channel should this be published to"
    required: false
outputs:
  slack-message-id:
    description: "Slack message id that was published"
    value: ${{ steps.slack-notifier.outputs.SLACK_MESSAGE_ID }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download changelog cli
      run: |
        curl -L -o slack-notifier-cli https://github.com/monta-app/slack-notifier-cli/releases/download/v1.0.1/slack-notifier-cli
        chmod +x ./slack-notifier-cli
      shell: bash
    - name: Run slack notifier cli
      id: slack-notifier
      env:
        PUBLISH_SLACK_STATUS: ${{ inputs.status }}
        PUBLISH_SLACK_TITLE: ${{ inputs.title }}
        SLACK_TOKEN: ${{ inputs.slack-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        SLACK_MESSAGE_ID: ${{ inputs.slack-message-id }}
      run: ./slack-notifier-cli
      shell: bash
