name: "Slack Notifier CLI"
description: "Create a change log based of git commit history"
inputs:
  github-context:
    description: ""
    required: true
  job-type:
    description: ""
    required: true
  job-status:
    description: ""
    required: true
  slack-app-token:
    description: ""
    required: true
  slack-channel-id:
    description: ""
    required: true
  slack-message-id:
    description: ""
    required: false
outputs:
  slack-message-id:
    description: "Slack message id that was published"
    value: ${{ steps.slack-notifier.outputs.SLACK_MESSAGE_ID }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Download changelog cli
      run: |
        curl -L -o slack-notifier-cli https://github.com/monta-app/slack-notifier-cli/releases/download/v1.0.4/slack-notifier-cli
        chmod +x ./slack-notifier-cli
      shell: bash
    - name: Run slack notifier cli
      id: slack-notifier
      env:
        PUBLISH_SLACK_GITHUB_CONTEXT: ${{ inputs.github-context }}
        PUBLISH_SLACK_JOB_TYPE: ${{ inputs.job-type }}
        PUBLISH_SLACK_JOB_STATUS: ${{ inputs.job-status }}
        SLACK_APP_TOKEN: ${{ inputs.slack-app-token }}
        SLACK_CHANNEL_ID: ${{ inputs.slack-channel-id }}
        SLACK_MESSAGE_ID: ${{ inputs.slack-message-id }}
      run: ./slack-notifier-cli
      shell: bash
