apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  # Name of the project 
  name: slack-notifier-cli-action
  description: N/A
  # Specifies the directory of the docs
  annotations:
    backstage.io/techdocs-ref: dir:.

  # TODO: Please set the service tier manually,
  # See notion page for more info: https://www.notion.so/montaapp/Service-Tiers-035d974e192d496a962f409bc0808a53?pvs=4
  labels:
    tier: '3'

  # These links are just examples, set them to what you think is the most relevant.
  links:
    # Slack channel to write in for communicating with the resposible team.
  - title: Team Slack Channel
    url: https://monta-app01.slack.com/archives/C02NQ35QS8Z
    type: Slack
    icon: chat
    # Page in notion documenting the purpose and function of the service 
  - title: Notion
    url: https://www.notion.so/montaapp/slack-notifier-cli-action-f64d469c3a1b487a969ed799718b5632?pvs=4
    type: Notion
    icon: docs
   
# The spec defines who becomes the owner of the system in backstage
spec:
  type: cli
  lifecycle: production
  # Name of the squad responsible for the project, e.g. sre or cpi
  owner: SRE
  # Name of the greater system, e.g. "solar" is a part of the home system
  system: Platform
